.\" generated with Ronn-NG/v0.9.0
.\" http://github.com/apjanke/ronn-ng/tree/0.9.0
.TH "GO\-SENDXMPP" "5" "April 2020" ""
.SH "NAME"
\fBgo\-sendxmpp\fR \- A little tool to send messages to an XMPP contact or MUC\.
.SH "LOCATION"
The account data is expected at ~/\.sendxmpprc if no other configuration file location is specified with \-f or \-\-file\. The configuration file is expected to be in the following format:
.SH "FORMAT"
username: [\fIyour_username\fR]
.br
jserver: [\fIjabber_server\fR]
.br
port: [\fIjabber_port\fR]
.br
password: [\fIyour_jabber_password\fR]
.SH "AUTHOR"
Written by Martin Dosch\.
.SH "REPORTING BUGS"
Report bugs at https://salsa\.debian\.org/mdosch/go\-sendxmpp/issues
.SH "COPYRIGHT"
Copyright (c) 2018 \- 2020 Martin Dosch License: BSD 2\-clause License
.SH "SEE ALSO"
go\-sendxmpp(1), sendxmpp(1)
